# permissions for end users to edit githubissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: githubissuer-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: github-issuer
    app.kubernetes.io/part-of: github-issuer
    app.kubernetes.io/managed-by: kustomize
  name: githubissuer-editor-role
rules:
- apiGroups:
  - github.benda.io
  resources:
  - githubissuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - github.benda.io
  resources:
  - githubissuers/status
  verbs:
  - get
