---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - github.benda.io
  resources:
  - githubissuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - github.benda.io
  resources:
  - githubissuers/finalizers
  verbs:
  - update
- apiGroups:
  - github.benda.io
  resources:
  - githubissuers/status
  verbs:
  - get
  - patch
  - update
